version: "3"

services:
  principal:
    container_name: principal
    command: --port 8080 --threshold 10 --rate 10s --timeout 60s --container http-echo --debug
    image: principal:latest
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  http-echo:
    container_name: http-echo
    image: hashicorp/http-echo
    command: -listen=:8080 -text="hello world"
    depends_on:
      - principal
    network_mode: service:principal
