name: "Check"

on:
  workflow_dispatch:
  push:

jobs:
  check-nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Format flake.nix
        run: nix run nixpkgs#nixpkgs-fmt -- flake.nix --check

  check-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy

      - name: Check formatting
        run: rustfmt --check

      - name: Check clippy
        run: cargo clippy -- -Dclippy::all -Dclippy::pedanti
